export const mockRestaurants = [
  {
    id: "1",
    name: "Spice Villa",
    cuisine: "Indian",
    rating: 4.6,
    deliveryTime: "30-40 mins",
    deliveryFee: 40,
    location: "Downtown",
    address: "123 MG Road, Downtown, Bangalore - 560001",
    phone: "+91 80 1234 5678",
    description: "Authentic Indian cuisine with traditional recipes",
    imageUrl: "/indian-restaurant-exterior.jpg",
    menu: [
      {
        id: "1-1",
        name: "Samosa",
        category: "Starters",
        price: 80,
        description: "Crispy triangular pastry with potato filling",
        imageUrl: "/crispy-golden-samosas.png",
      },
      {
        id: "1-2",
        name: "Paneer Tikka",
        category: "Starters",
        price: 180,
        description: "Marinated paneer chunks grilled to perfection",
        imageUrl: "/paneer-tikka.png",
      },
      {
        id: "1-3",
        name: "Butter Chicken",
        category: "Mains",
        price: 320,
        description: "Tender chicken in creamy tomato sauce",
        imageUrl: "/butter-chicken.jpg",
      },
      {
        id: "1-4",
        name: "Biryani",
        category: "Mains",
        price: 280,
        description: "Fragrant rice cooked with meat and spices",
        imageUrl: "/flavorful-biryani.png",
      },
      {
        id: "1-5",
        name: "Gulab Jamun",
        category: "Desserts",
        price: 120,
        description: "Soft milk solids in sugar syrup",
        imageUrl: "/gulab-jamun.png",
      },
    ],
  },
  {
    id: "2",
    name: "Burger Hub",
    cuisine: "American",
    rating: 4.4,
    deliveryTime: "20-30 mins",
    deliveryFee: 30,
    location: "Midtown",
    address: "456 Brigade Road, Midtown, Bangalore - 560025",
    phone: "+91 80 2345 6789",
    description: "Premium burgers and American fast food",
    imageUrl: "/burger-restaurant.jpg",
    menu: [
      {
        id: "2-1",
        name: "Cheese Fries",
        category: "Starters",
        price: 120,
        description: "Crispy fries with melted cheese",
        imageUrl: "/cheese-fries.jpg",
      },
      {
        id: "2-2",
        name: "Chicken Wings",
        category: "Starters",
        price: 200,
        description: "Spicy buffalo chicken wings",
        imageUrl: "/chicken-wings.jpg",
      },
      {
        id: "2-3",
        name: "Classic Burger",
        category: "Mains",
        price: 250,
        description: "Juicy beef patty with fresh toppings",
        imageUrl: "/classic-beef-burger.png",
      },
      {
        id: "2-4",
        name: "BBQ Bacon Burger",
        category: "Mains",
        price: 320,
        description: "Smoky BBQ with crispy bacon",
        imageUrl: "/bbq-burger.jpg",
      },
      {
        id: "2-5",
        name: "Chocolate Shake",
        category: "Desserts",
        price: 150,
        description: "Thick and creamy chocolate milkshake",
        imageUrl: "/chocolate-shake.jpg",
      },
    ],
  },
  {
    id: "3",
    name: "Sushi Zen",
    cuisine: "Japanese",
    rating: 4.8,
    deliveryTime: "35-45 mins",
    deliveryFee: 50,
    location: "Harbor District",
    address: "789 Indiranagar, Harbor District, Bangalore - 560038",
    phone: "+91 80 3456 7890",
    description: "Fresh sushi and Japanese delicacies",
    imageUrl: "/sushi-restaurant.jpg",
    menu: [
      {
        id: "3-1",
        name: "Edamame",
        category: "Starters",
        price: 100,
        description: "Steamed soybeans with sea salt",
        imageUrl: "/edamame-bowl.png",
      },
      {
        id: "3-2",
        name: "Gyoza",
        category: "Starters",
        price: 140,
        description: "Pan-fried pork dumplings",
        imageUrl: "/delicious-gyoza.png",
      },
      {
        id: "3-3",
        name: "California Roll",
        category: "Mains",
        price: 280,
        description: "Avocado, crab, and cucumber in sushi rice",
        imageUrl: "/california-roll.jpg",
      },
      {
        id: "3-4",
        name: "Dragon Roll",
        category: "Mains",
        price: 350,
        description: "Eel, cucumber, avocado with unique presentation",
        imageUrl: "/dragon-roll.jpg",
      },
      {
        id: "3-5",
        name: "Mochi Ice Cream",
        category: "Desserts",
        price: 130,
        description: "Chewy mochi with ice cream inside",
        imageUrl: "/mochi-ice-cream.png",
      },
    ],
  },
  {
    id: "4",
    name: "Tandoor Palace",
    cuisine: "Indian",
    rating: 4.5,
    deliveryTime: "35-40 mins",
    deliveryFee: 45,
    location: "South End",
    address: "321 Koramangala, South End, Bangalore - 560095",
    phone: "+91 80 4567 8901",
    description: "Traditional tandoori and north Indian specialties",
    imageUrl: "/tandoor-restaurant.jpg",
    menu: [
      {
        id: "4-1",
        name: "Onion Bhaji",
        category: "Starters",
        price: 90,
        description: "Crispy onion fritters",
        imageUrl: "/onion-bhaji.jpg",
      },
      {
        id: "4-2",
        name: "Chicken Tikka",
        category: "Starters",
        price: 200,
        description: "Marinated chicken pieces cooked in tandoor",
        imageUrl: "/chicken-tikka.jpg",
      },
      {
        id: "4-3",
        name: "Tandoori Chicken",
        category: "Mains",
        price: 350,
        description: "Whole chicken marinated and tandoor-cooked",
        imageUrl: "/tandoori-chicken.jpg",
      },
      {
        id: "4-4",
        name: "Dal Makhani",
        category: "Mains",
        price: 220,
        description: "Creamy lentils with butter and cream",
        imageUrl: "/dal-makhani.jpg",
      },
      {
        id: "4-5",
        name: "Kheer",
        category: "Desserts",
        price: 100,
        description: "Rice pudding with nuts and cardamom",
        imageUrl: "/creamy-kheer.png",
      },
    ],
  },
];

export type MenuItem = (typeof mockRestaurants)[0]["menu"][0];
export type Restaurant = (typeof mockRestaurants)[0];
